In [ ]:
import numpy as np
import pandas as pd
import os
import seaborn as sns
import matplotlib.pyplot as plt
import sklearn.linear_model as lm

In [ ]:
data=pd.read_csv('weight-height.csv')
data.head()

  Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

In [ ]:
print(data.shape)
data.describe()

(10000, 3)

             Height        Weight
count  10000.000000  10000.000000
mean      66.367560    161.440357
std        3.847528     32.108439
min       54.263133     64.700127
25%       63.505620    135.818051
50%       66.318070    161.212928
75%       69.174262    187.169525
max       78.998742    269.989699

In [ ]:
data.corr()

          Height    Weight
Height  1.000000  0.924756
Weight  0.924756  1.000000

In [ ]:
lr=lm.LinearRegression() 
lr.fit(Height,Weight)

NameError: ignored